### PR TITLE
Admin dashboard and namespacing

### PR DESCRIPTION
**Pull request by AllPurposeName**

### CODE REVIEW

**Comment by AllPurposeName** [comment]
Please close the waffle issues when you get to mergin this, thanks yo

**Comment by AllPurposeName** [comment]
Please close the waffle issues when you get to mergin this, thanks yo

**Comment by blocknroll** [comment]
All good to go...by Fred!

**Comment by xvalentino** [comment]
Do we want to surrender to Hound and user double quoted strings instead of single quoted?

**Pull request merged**
